### ISSUE TITLE
Problem: can't build ca-certificate due to missing certifi in conda build environment

### ISSUE THREAD

**Issue by argltuc** [conda-forge/ca-certificates-feedstock#14]
I just want to build ca-certificate on my own, based on an also own builded certifi from certifi-feedstocks.
But at the beginning of the build process I got this error:

```
+ cp -f /home/argl/miniconda3/conda-bld/ca-certificates_1487077552698/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.5/site-packages/certifi/cacert.pem /home/argl/miniconda3/conda-bld/ca-certificates_1487077552698/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/ssl
cp:cannot stat '/home/argl/miniconda3/conda-bld/ca-certificates_1487077552698/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.5/site-packages/certifi/cacert.pem': No such file or directory
```

Why does it passed your CI but doesn't build on my home machine? Is there some configuration or package missing?
I'm working on ubuntu 16.04 lts with conda 4.3.11 and conda-build 2.1.4

**Comment by jakirkham** [comment]
Not sure. Did you inspect the contents of the `certifi` package? Does it actually have the certificates?

That all being said, I think the current build process here is overly complicated. So am proposing we just build this package direct from `certifi`'s source and cut out these steps inbetween. Would expect that alleviates the issues you experience here. Please take a look at PR ( https://github.com/conda-forge/ca-certificates-feedstock/pull/17 ) for details.

**Comment by argltuc** [comment]
Yes, in the package content of certifi 2017.1.23_py35 are some *.pem-files and with them cacert.pem under site-packages/certifi-2017.1.23-py3.5.egg/certifi.
How ever, I quickly try your new branch and got it work as I expected.
So this issues seems to be obsolete due to the new commits of #17 .
Thanks
