### ISSUE TITLE
MD5 checksum mismatch in anaconda.org

### ISSUE THREAD

**Issue by wesm** [conda-forge/ca-certificates-feedstock#21]
Getting errors like these today in Appveyor

```
CondaError: MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/conda-forge/win-64/ca-certificates-2017.7.27.1-0.tar.bz2'.
  download saved to: C:\Miniconda35-x64\pkgs\ca-certificates-2017.7.27.1-0.tar.bz2
  expected md5 sum: 82f94cae7099aa1a16275eafa4fc11dd
  actual md5 sum: 94762f40f9b70670f402f624ab2e5337
```

I worry this might be related to the metadata editing stuff that has been going on for a while, ideas?

**Comment by ocefpaf** [comment]
I am getting this error for other packages and other platforms too. I hope it is a temporary network issue.

Ping @msarahan, @jjhelmus, and @mingwandroid (sorry for the mass guys spam, don't know who we should ping for a anaconda.org issue like that :smile:)

**Comment by jakirkham** [comment]
Interesting! A coworker mentioned seeing a similar issue earlier (though with different packages), but I had not read this at the time. So I don't think it is unique to `ca-certificates`.

We tried cleaning the index cache `conda clean -i`, which resolved the issue for him. Not sure if the same strategy would work for anyone here.

cc @stuarteberg

**Comment by jakirkham** [comment]
As evidence that this is not unique to `ca-certificates`, please see issue ( https://github.com/conda-forge/bzip2-feedstock/issues/2 ), which is the same story with `bzip2`.

**Comment by msarahan** [comment]
I have pointed the anaconda.org team to this issue.  They have been fighting some high resource usage due to some abusive users, and needed to revert to earlier code that may have caused this relapse.  I'm told that this issue is fixed for them as of this morning.

**Comment by ocefpaf** [comment]
Thanks @msarahan! (I hope the abuse users are not us :smile:)
