### ISSUE TITLE
OpenSSL issues since recent miniconda update in last 48 hours

### ISSUE THREAD

**Issue by wesm** [conda-forge/ca-certificates-feedstock#22]
We've been experiencing HTTPS issues in libcurl in the last 48 hours since Miniconda was updated. see

https://github.com/apache/arrow/pull/1155#issuecomment-334151619

the only change I can honestly see is that miniconda is now installing a newer ca-certificates in defaults.

I know I've said it before, but having the root Miniconda outside of conda-forge's governance makes me deeply uncomfortable, because stuff can get broken unilaterally by a single corporation with very little recourse for us.

**Comment by jakirkham** [comment]
So we don't produce Miniconda. They also have their own copy of `ca-certificates`.

Could you please raise this issue on this [repo]( https://github.com/ContinuumIO/anaconda-issues ) and see what they say? Would be curious to know what you find out.

**Comment by wesm** [comment]
Will do. Forcing the defaults ca-certificates fixed the build failure FWIW https://github.com/apache/arrow/pull/1160

**Comment by jakirkham** [comment]
Thanks @wesm. I don't have time to dig into it right now unfortunately. If you have a workaround, would go with it for now until we can sort it out.

Though it would be good to have a simple reproducer outside of CI that I or someone else can dig into further. Is there some issue that can be shown with `curl` in a basic `conda` environment after this upgrade for instance?

There is really not a lot going on in this package. So it is a bit baffling that either ours or Anaconda's would have something wrong with it. The only thing I could even guess would be `conda` has some new behavior with handling soft links. However until we test it, we can't be sure.

**Comment by wesm** [comment]
I'll see if I can make a standalone repro for you; from our CI setup it should only involve copy-pasting a couple things and using curl on an HTTPS link from github to blow things up

**Comment by jakirkham** [comment]
That would be great. Thanks @wesm!

**Comment by wesm** [comment]
With a half hour of trying I haven't been able to repro this in a Dockerfile, so it may have something to do with the Travis CI Trusty image. I will tinker later today...

**Comment by jakirkham** [comment]
If you can repro it outside the Docker image, that could still be interesting as well.

**Comment by jakirkham** [comment]
Is this still an issue?

**Comment by wesm** [comment]
Haven't seen since this time, so I will close
