### ISSUE TITLE
Where can I see the license file for the ca-certificates package

### ISSUE THREAD

**Issue by stevehaertel** [conda-forge/ca-certificates-feedstock#34]
**Package license: ISC**

1. Where can I see the license file for the ca-certificates package? 
2. Is the license a default one, or does it have some customization, like copyrights, etc.

**Comment by jakirkham** [comment]
Generally if a license file is included in the package (as is the case here), you can find it at `info/LICENSE.txt` within the decompressed package. All packages you install will live somewhere called the package cache (`<Path to Miniconda>/pkgs` by default) so license files can be found in the packages there.

**Comment by stevehaertel** [comment]
> Generally if a license file is included in the package (as is the case here), you can find it at `info/LICENSE.txt` within the decompressed package. All packages you install will live somewhere called the package cache (`<Path to Miniconda>/pkgs` by default) so license files can be found in the packages there.

That is not the case in Anaconda 2019.03:

`[root@server pkgs]# cat ./ca-certificates-2019.1.23-0/info/
about.json            files                 git                   hash_input.json       index.json            paths.json            recipe/               repodata_record.json`

**Comment by jakirkham** [comment]
Is that the conda-forge package or is that coming from another channel (e.g. defaults)?

**Comment by stevehaertel** [comment]
Is there a way to find out? I just installed Anaconda 2019.3 without doing anything special, and this package shows up in my packages in my base environment all by itself.

Here is the content of the repodata_record.json, if that help figure out where it came from:

`[root@server pkgs]# cat ./ca-certificates-2019.1.23-0/info/repodata_record.json
{
  "build": "0",
  "build_number": 0,
  "channel": "https://repo.anaconda.com/pkgs/main/linux-64",
  "constrains": [],
  "depends": [],
  "features": "",
  "fn": "ca-certificates-2019.1.23-0.tar.bz2",
  "license": "ISC",
  "md5": "68eed18f420722007d6e45758766c1e4",
  "name": "ca-certificates",
  "size": 129401,
  "subdir": "linux-64",
  "timestamp": 1549469958294,
  "track_features": "",
  "url": "https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2019.1.23-0.tar.bz2",
  "version": "2019.1.23"`

**Comment by jakirkham** [comment]
Running `conda list ca-certificates` wherever the package is installed should work.

If you just installed Anaconda, then it is coming from `defaults`. Installing from `conda-forge` is an extra step. Also the repodata supplied shows this package is coming from `defaults`. Note the `channel` points to `main`, which is part of `defaults`.

Given this is coming from `defaults`, would [raise an issue here]( https://github.com/AnacondaRecipes/ca-certificates-feedstock/issues ). Looking at the recipe for `defaults` it does seem the license file is not included. Normally one would see [a line like this one]( https://github.com/conda-forge/ca-certificates-feedstock/blob/bdef0307f764fb16fa105363cbe6719317838909/recipe/meta.yaml#L32 ).

**Comment by stevehaertel** [comment]
Thank you for the confirmation jakirkham. I'll raise an issue, but I guess that will only solve future licensing issues. As far as it stands now, I was asked with finding the licenses/copyrights for the default packages for Anaconda2019.3 for my organization, and I'm going to have to come back and say that I did my due diligence and refer to the default ISC license https://opensource.org/licenses/ISC with has the copyright string "Copyright <YEAR> <OWNER>".

It's not so much a problem for me, but rather if that is important for the developers of this package, it might be something that they want to fix.

**Comment by jakirkham** [comment]
Sure, happy to help. Please link the raised issue here for tracking purpose if you don't mind.

My guess is Anaconda will appreciate the feedback on which packages are missing license files. It may be worthwhile to just deliver them a full list of all the packages you see without licenses and [raise a meta issue here]( https://github.com/AnacondaRecipes/aggregate/issues ) (since that sounds like what you are collecting anyways).

**Comment by stevehaertel** [comment]
Issue I opened for AnacondaRecipes/ca-certificates-feedstock:

https://github.com/AnacondaRecipes/ca-certificates-feedstock/issues/3
