### ISSUE TITLE
How is `ca-certificates` different from `certifi`?

### ISSUE THREAD

**Issue by zzhengnan** [conda-forge/ca-certificates-feedstock#53]
### Comment:

I'm curious about the difference between `ca-certificates` and `certifi`. 

Based on their respective feedstocks, both packages source from the PyPI `certifi` package. Why do we need both?
- Feedstock for `ca-certificates`: https://github.com/conda-forge/ca-certificates-feedstock/blob/573efebacae4c7d31c502301559a4ba546309e71/recipe/meta.yaml#L8
- Feedstock for `certifi`:
https://github.com/conda-forge/certifi-feedstock/blob/3ded6d99cd0a88255ad01cb6d0ae1f54a6a086f1/recipe/meta.yaml#L11

**Comment by jakirkham** [comment]
`ca-certificates` just pulls out the certificates from `certifi` and uses them (so none of the Python code). These are then placed in a standard location where other libraries & tools (like `openssl` and `git` can find them).

It is worth noting that end users could create their own `ca-certificates` package on their own channel (giving that higher priority in Conda solves) and effectively use a different set of certificates if they prefer.

**Comment by zzhengnan** [comment]
Thanks for the clarification, John.
